import type { Metadata } from 'next';
import Link from 'next/link';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'AI Code Review · OWASP-Aware Reviewer Agents on Every PR | AGENA',
  description: 'Run AI code review on every pull request — OWASP-aware security agent, custom reviewer personas, severity scoring, and per-agent review history. Works with GitHub and Azure DevOps. Free tier available.',
  keywords: [
    'AI code review',
    'AI code review tool',
    'AI pull request review',
    'OWASP AI code review',
    'security AI code reviewer',
    'AI code review GitHub',
    'AI code review Azure DevOps',
    'custom reviewer agent AI',
    'CodeRabbit alternative',
    'PullPanda alternative',
    'GitHub Copilot review alternative',
  ],
  alternates: { canonical: 'https://agena.dev/ai-code-review' },
  openGraph: {
    type: 'article',
    url: 'https://agena.dev/ai-code-review',
    title: 'AI Code Review — OWASP-Aware Reviewer Agents | AGENA',
    description: 'Custom reviewer agents (security, performance, accessibility) run on every PR. Severity scores, per-agent history, no source code leaves your control.',
    images: ['/og-image.png'],
  },
};

const FAQ = [
  {
    q: 'How does AGENA do AI code review?',
    a: 'You define one or more reviewer agents in AGENA — each with its own role (reviewer, security_developer, qa, lead_developer), system prompt, model, and provider. When a task is generated by AI or imported from Sentry / Jira / Azure DevOps, the chosen reviewer agent runs against the diff and writes a structured report with summary, findings (file/line, severity, fix), severity verdict, and a 0-100 confidence score.',
  },
  {
    q: 'What is the OWASP-aware reviewer?',
    a: 'A pre-built reviewer agent (security_developer) shipped with AGENA. Its system prompt is paranoid by default: treats every input as malicious, checks for OWASP Top 10 vulnerabilities (SQL injection, XSS, SSRF, auth bypass, deserialization), and produces threat model + fix plan + residual risk note. You can customize the prompt in Prompt Studio.',
  },
  {
    q: 'Can I create my own reviewer personas?',
    a: 'Yes — go to /dashboard/agents and create an agent with the is_reviewer flag on. Pick its model (GPT-5, Gemini, Claude), provider, and write a custom system prompt. Reviewer agents appear in the reviewer picker on every task.',
  },
  {
    q: 'Does the AI review block PR merge?',
    a: 'It does not block by default — reviews are advisory and posted as comments + a structured Findings section in the PR description. You can configure required reviewers / branch protection in GitHub or Azure DevOps to block on a specific severity threshold via webhook.',
  },
  {
    q: 'How is this different from CodeRabbit / GitHub Copilot review?',
    a: 'AGENA reviewers are configurable agents, not a single fixed model. Each persona has its own prompt and can run different models for cost/quality tradeoffs. Reviews are auditable per agent with full history. And you can route different ticket types to different reviewer agents (security tickets → security_developer; refactor tickets → lead_developer).',
  },
  {
    q: 'Where is the source code sent?',
    a: 'Only the diff and the file:line context window are sent to the LLM provider you chose for that reviewer agent (OpenAI, Anthropic, Google, or your self-hosted endpoint). AGENA does not retain code or train on it. You can run AGENA self-hosted for full air-gapped operation.',
  },
];

export default function AICodeReviewPage() {
  const ldJson = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'AGENA — AI Code Review',
    applicationCategory: 'DeveloperApplication',
    operatingSystem: 'Web',
    description: metadata.description,
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    publisher: { '@type': 'Organization', name: 'AGENA', url: 'https://agena.dev' },
  };
  const faqJson = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQ.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };

  return (
    <main style={{ maxWidth: 980, margin: '0 auto', padding: '40px 20px', display: 'grid', gap: 48 }}>
      <Script id='ld-app' type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(ldJson) }} />
      <Script id='ld-faq' type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJson) }} />

      <header style={{ textAlign: 'center' }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: '#10b981', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 12 }}>
          AI Code Review
        </div>
        <h1 style={{ fontSize: 'clamp(28px, 5vw, 46px)', fontWeight: 800, lineHeight: 1.1, color: 'var(--ink-90)', margin: 0 }}>
          OWASP-aware AI reviewer agents <br />
          <span style={{ background: 'linear-gradient(90deg, #10b981, #06b6d4)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' }}>on every pull request</span>
        </h1>
        <p style={{ fontSize: 17, color: 'var(--ink-58)', marginTop: 18, maxWidth: 720, marginInline: 'auto', lineHeight: 1.55 }}>
          Define your own reviewer agents — security, performance, accessibility, lead developer — each with its own
          system prompt and model. Route security tickets to the security reviewer automatically. Severity score,
          findings list, per-agent audit history.
        </p>
        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', marginTop: 24, flexWrap: 'wrap' }}>
          <Link href='/signup' style={{ padding: '12px 24px', borderRadius: 10, background: 'linear-gradient(135deg, #10b981, #06b6d4)', color: '#fff', fontSize: 14, fontWeight: 700, textDecoration: 'none' }}>
            Start free — try the reviewer
          </Link>
          <Link href='/dashboard/reviews' style={{ padding: '12px 24px', borderRadius: 10, border: '1px solid var(--panel-border)', background: 'var(--panel)', color: 'var(--ink)', fontSize: 14, fontWeight: 700, textDecoration: 'none' }}>
            See review history →
          </Link>
        </div>
      </header>

      <section>
        <h2 style={{ fontSize: 24, fontWeight: 800, marginBottom: 16 }}>How it works</h2>
        <ol style={{ display: 'grid', gap: 12, paddingLeft: 0, listStyle: 'none' }}>
          {[
            { title: 'Create reviewer agents', desc: 'Go to /dashboard/agents → New Agent. Toggle is_reviewer on. Pick a role (reviewer / security_developer / qa / lead_developer), a model (GPT-5, Gemini, Claude), and a system prompt. Save.' },
            { title: 'Pick a reviewer per task', desc: 'On any task, click 🔎 Review. Pick "✨ Auto" to let Agena resolve the role from task tags / Integration Rules, or pick a specific reviewer agent. The review runs synchronously (single LLM call, no code mutation).' },
            { title: 'Read the structured report', desc: 'Every review produces: ### Summary (1-2 sentences), ### Findings (numbered list with file/line, severity, fix), ### Severity (critical/high/medium/low/clean), ### Score (0-100 confidence to merge).' },
            { title: 'Audit history per agent', desc: 'Open the agent card. See severity distribution, average score, and full history of every review the agent has done — across tasks, tags, and time.' },
            { title: 'Or run as a flow node', desc: 'Drop the reviewer node in any flow (visual builder). Use the score / severity output as a condition gate to auto-merge clean PRs and hold critical ones for human review.' },
          ].map((step, i) => (
            <li key={i} style={{ display: 'flex', gap: 16, padding: '14px 18px', borderRadius: 12, background: 'var(--panel)', border: '1px solid var(--panel-border)' }}>
              <div style={{ width: 32, height: 32, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(16,185,129,0.15)', color: '#34d399', fontWeight: 800, flexShrink: 0 }}>{i + 1}</div>
              <div>
                <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--ink-90)' }}>{step.title}</div>
                <div style={{ fontSize: 13, color: 'var(--ink-58)', marginTop: 4, lineHeight: 1.55 }}>{step.desc}</div>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section>
        <h2 style={{ fontSize: 24, fontWeight: 800, marginBottom: 16 }}>What sets AGENA reviewers apart</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 }}>
          {[
            { icon: '🛡️', title: 'OWASP-aware out of the box', body: 'security_developer agent ships with a paranoid OWASP Top 10 prompt: SQLi, XSS, SSRF, auth bypass, insecure deserialization.' },
            { icon: '🎭', title: 'Custom reviewer personas', body: 'Build any persona: Performance Reviewer, Accessibility Reviewer, SQL Style Cop, Frontend State Reviewer. Each gets its own prompt + model.' },
            { icon: '🔢', title: 'Severity + score', body: 'Every review produces a severity (critical/high/medium/low/clean) and a 0-100 confidence score. Use as gating signal in flows or branch protection.' },
            { icon: '📊', title: 'Per-agent history', body: 'Each reviewer agent has a review history banner: severity distribution, avg score, click-through to past reports. Great for performance reviews.' },
            { icon: '🔀', title: 'Auto-routing', body: 'Integration Rules pick the right reviewer based on Sentry tags, Jira reporter, Azure area path, NewRelic entity, or task labels.' },
            { icon: '💰', title: 'Pick the right model per agent', body: 'Run cheap GPT-5-mini for refactor reviews and premium GPT-5-pro for security reviews. Cost is yours, quality is configurable.' },
            { icon: '🧠', title: 'Prompt Studio', body: 'Edit reviewer system prompts at runtime. Roll back to previous versions. Test against a sample task before saving.' },
            { icon: '🔒', title: 'No code retention', body: 'Diff is sent to the LLM you chose. AGENA never trains on your code. Run self-hosted for fully air-gapped reviews.' },
          ].map((f) => (
            <div key={f.title} style={{ padding: 16, borderRadius: 12, background: 'var(--panel)', border: '1px solid var(--panel-border)' }}>
              <div style={{ fontSize: 22, marginBottom: 8 }}>{f.icon}</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink-90)' }}>{f.title}</div>
              <div style={{ fontSize: 12, color: 'var(--ink-58)', marginTop: 6, lineHeight: 1.55 }}>{f.body}</div>
            </div>
          ))}
        </div>
      </section>

      <section style={{ padding: 24, borderRadius: 16, background: 'var(--panel)', border: '1px solid var(--panel-border)' }}>
        <h2 style={{ fontSize: 22, fontWeight: 800, marginBottom: 12 }}>Sample reviewer output</h2>
        <pre style={{ fontFamily: 'ui-monospace, monospace', fontSize: 12, color: 'var(--ink-78)', background: 'rgba(0,0,0,0.2)', padding: 16, borderRadius: 10, overflowX: 'auto', lineHeight: 1.6, margin: 0 }}>{`### Summary
The patch fixes the off-by-one in pagination but introduces a SQL string concat that is reachable from /api/orders.

### Findings
1. packages/services/src/agena_services/services/order_service.py:88 — SQL injection (CRITICAL).
   String concatenation builds the WHERE clause from a request parameter. Use a parameterized query.
   Fix: replace f-string with text(":order_id") and pass {"order_id": order_id} to .execute().
2. packages/api/src/agena_api/api/routes/orders.py:42 — Missing authentication decorator (HIGH).
   The /orders/{id}/refund endpoint has no Depends(get_current_user). Anyone can hit it.
3. tests/test_orders.py:120 — Test asserts side effect on the wrong fixture (LOW).

### Severity
critical

### Score
24`}</pre>
      </section>

      <section>
        <h2 style={{ fontSize: 24, fontWeight: 800, marginBottom: 16 }}>Frequently asked</h2>
        <div style={{ display: 'grid', gap: 10 }}>
          {FAQ.map((f) => (
            <details key={f.q} style={{ padding: '12px 16px', borderRadius: 10, background: 'var(--panel)', border: '1px solid var(--panel-border)' }}>
              <summary style={{ cursor: 'pointer', fontSize: 14, fontWeight: 700, color: 'var(--ink-90)' }}>{f.q}</summary>
              <p style={{ fontSize: 13, color: 'var(--ink-58)', marginTop: 8, lineHeight: 1.6 }}>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      <footer style={{ textAlign: 'center', padding: '40px 0', borderTop: '1px solid var(--panel-border)' }}>
        <h2 style={{ fontSize: 22, fontWeight: 800, marginBottom: 12 }}>Catch the SQL injection before merge</h2>
        <p style={{ fontSize: 14, color: 'var(--ink-58)', maxWidth: 560, margin: '0 auto 20px' }}>
          OWASP-aware reviewer agents on the free tier. Bring your own LLM key. Self-hostable for air-gapped review.
        </p>
        <Link href='/signup' style={{ padding: '12px 28px', borderRadius: 10, background: 'linear-gradient(135deg, #10b981, #06b6d4)', color: '#fff', fontSize: 14, fontWeight: 700, textDecoration: 'none', display: 'inline-block' }}>
          Start free
        </Link>
      </footer>
    </main>
  );
}
